mytestkey=This value is from LOCAL properties file

paypal.clientId=YOUR_PAYPAL_CLIENT_ID
paypal.clientSecret=YOUR_PAYPAL_CLIENT_SECRET
paypal.oAuthUrl=https://api-m.sandbox.paypal.com/v1/oauth2/token

paypal.createOrderUrl=https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.getOrderUrl=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}
paypal.captureOrderUrl=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture

spring.ai.openai.api-key=YOUR-OPENAPI-KEY
spring.ai.openai.chat.options.model=gpt-3.5-turbo

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true

