mytestkey=This value is from LOCAL properties file


	
paypal.clientId=AVmpAgpBHO8AiFcxKt5_-6RNvagTJx9wUf7mvRh81PauHH44BULW9ChYd_nV0E-BbR26z6pKRia83g4E
paypal.clientSecret=EKkRbY_5ef9nooVBmhu3UpCHVyHEtXVJqlOjK8CunMyIi8ns34pCKLr8Cv1RoY6NMvU_cPT9ICBg5CFJ
paypal.oAuthUrl=https://api-m.sandbox.paypal.com/v1/oauth2/token

paypal.createOrderUrl=https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.getOrderUrl=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}
paypal.captureOrderUrl=https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture


 
## ========== Eureka Server Configuration ==========
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.server.wait-time-in-ms-when-sync-empty=0
