mytestkey=This value is from DEV properties file

	
paypal.clientId=AVmpAgpBHO8AiFcxKt5_-6RNvagTJx9wUf7mvRh81PauHH44BULW9ChYd_nV0E-BbR26z6pKRia83g4E
paypal.clientSecret=EKkRbY_5ef9nooVBmhu3UpCHVyHEtXVJqlOjK8CunMyIi8ns34pCKLr8Cv1RoY6NMvU_cPT9ICBg5CFJ
paypal.oAuthUrl=https://api-m.sandbox.paypal.com/v1/oauth2/token